# Generated by Django 5.1.1 on 2024-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="specialization",
            field=models.CharField(
                default=12, max_length=150, unique=True, verbose_name="Специализация"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Группа"),
        ),
    ]
