# Generated by Django 5.1.1 on 2024-10-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_specialization_alter_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Группа'),
        ),
    ]
