# Generated by Django 5.1.1 on 2024-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(default='Кафедра', max_length=150, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialization',
            field=models.CharField(max_length=150, verbose_name='Специализация'),
        ),
    ]
