# Generated by Django 5.1.1 on 2024-10-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_group_name_group_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.CharField(max_length=150, verbose_name='Кафедра'),
        ),
    ]
