# Generated by Django 5.1.1 on 2024-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_group_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="course",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Курс"),
        ),
    ]
