main:
  title:
    'Главная страница'
  text:
    'Это ваша платформа для отслеживания расписания занятий и информации о преподавателях.
     Система находится на стадии разработки. Будем рады услышать любую обратную связь!'
  email:
    'mv.yarmolovich@gmail.com'

users:
  profile:
    title:
      'Личный кабинет'
  groups:
    title:
      'Список групп'
  group_page:
    title:
      'Группа '
  teachers:
    title:
      'Список преподавателей'

lessons:
  schedule:
    title:
      'Расписание занятий'
  upload:
    title:
      'Загрузка занятий'
    error:
      'Ошибка при загрузке занятий:'
    type_error:
      'Имя файла не должно быть пустым.'
    success:
      "Занятия успешно загружены!"

dashboard:
  title: "Админ-панель"
  create_user:
    email_message:
      "Здравствуйте, {name}.\n\nВы зарегистрированы в системе расписания БГУКИ.\nДанные для входа:\n\nИмя пользователя:\n{username}\n\nПароль:\n{password}"
