# Generated by Django 5.1.1 on 2024-10-20 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "8:30 - 9:50"),
                            (1, "10:05 - 11:25"),
                            (2, "12:00 - 13:20"),
                            (3, "13:35 - 14:55"),
                        ],
                        verbose_name="Номер занятия",
                    ),
                ),
                (
                    "start",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Начало",
                    ),
                ),
                (
                    "end",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Конец",
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("л.", "Лекция"),
                            ("пр.", "Практическая"),
                            ("лаб.", "Лабораторная"),
                            ("сем.", "Семинар"),
                            ("кардио", "Кардио"),
                            ("силовой", "Силовой"),
                            ("-", "Не указан"),
                        ],
                        default="-",
                        max_length=10,
                        null=True,
                        verbose_name="Тип занятия",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "teacher",
                    models.CharField(max_length=150, verbose_name="Преподаватель"),
                ),
                (
                    "subgroup",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Подгруппа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятия",
                "verbose_name_plural": "Занятия",
                "db_table": "lesson",
            },
        ),
    ]
