# Generated by Django 5.1.1 on 2024-10-05 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='День недели')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Номер занятия')),
                ('start', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Начало')),
                ('end', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Конец')),
                ('lesson_type', models.CharField(default='-', max_length=10, null=True, verbose_name='Тип занятия')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('teacher', models.CharField(max_length=150, verbose_name='Преподаватель')),
                ('subgroup', models.CharField(blank=True, max_length=20, null=True, verbose_name='Подгруппа')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Занятия',
                'db_table': 'lesson',
            },
        ),
    ]
