# Generated by Django 5.1.1 on 2024-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="number",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "8:30-9:50"),
                    (1, "10:05-11:25"),
                    (2, "12:00-13:20"),
                    (3, "13:35-14:55"),
                ],
                verbose_name="Номер занятия",
            ),
        ),
    ]
