# Generated by Django 5.1.1 on 2024-10-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятия', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('л.', 'Лекция'), ('пр.', 'Практическая'), ('лаб.', 'Лабораторная'), ('сем.', 'Семинар'), ('кардио', 'Кардио'), ('силовой', 'Силовой'), ('-', 'Не указан')], default='-', max_length=10, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(0, '8:30 - 9:50'), (1, '10:05 - 11:25'), (2, '12:00 - 13:20'), (3, '13:35 - 14:55')], verbose_name='Номер занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subgroup',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Подгруппа'),
        ),
    ]
